spring:
 application:
  name: flight-data-ms
 h2:
   console:
     enabled: true
 datasource:
   url: jdbc:h2:mem:flightdb
   username: sa
   password: sa
 config:
  server:
   git:
    default-label: master
   import: configserver:http://localhost:8888
server:
 port: 8081
zipkin:
 tracing:
  endpoint: "http://localhost:9411